### ISSUE TITLE
Refactor generic betydb functions to use new BETYdb API

### ISSUE THREAD

**Issue by dlebauer** [ropensci/traits#77]
## TODO
- [ ] remove `betydb_GET2` if it is redundant with `betydb_GET`
- [ ] rewrite `betydb_http`
  - [ ] remove old code for joining tables (lines starting with `includes <- list`. This joining method has been deprecated https://github.com/ropensci/traits/blob/master/R/betydb.R#L108
  - [ ] target API endpoint by version as paste0(betyurl, 'api')
- [ ] update vignette https://github.com/ropensci/traits/blob/master/vignettes/betydb.Rmd

* API documentation: https://www.betydb.org/api/docs/beta/
* Human readable https://pecan.gitbooks.io/betydb-data-access/content/API/beta_API.html

## Related Issues

It likely makes sense to tackle these at the same time:
- Add ability to query unchecked data from traits and yields tables #52
- refactoring the `betydb_<tablename>` functions is covered by #26; 
## References
- API description with examples: https://pecan.gitbooks.io/betydb-data-access/content/API/beta_API.html
- API Endpoint definitions: https://www.betydb.org/api/docs 
- The [original implementation](https://github.com/ropensci/traits/blob/4614aa1bc67cb46140403495b929137a56484706/R/betydb.R) of these functions by @sckott before I started hacking it up to allow the API joins that have since been deprecated.

**Comment by dlebauer** [comment]
Feedback appreciated @sckott @gsrhode @robkooper @max-zilla

**Comment by sckott** [comment]
@dlebauer thanks I'll have a look

**Comment by dlebauer** [comment]
@infotroph can this be closed?

**Comment by infotroph** [comment]
Yes, once #88 is merged. If we want to deprecate any of the table-specific functions (e.g. #26, #84) it may reduce user confusion to do it in the same release as we add the generics, but we should only deprecate them if we're sure we won't want them later (maybe for output standardization a la #38?). Your call.
